version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      npm: { patterns: ['*'] }
  - package-ecosystem: gradle
    directory: /apps/android
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /deployment/docker
    schedule: { interval: weekly }
