import type { WidgetManifest } from '@homedash/contracts';

export const widgetCatalog: WidgetManifest[] = [
  {
    id: 'clock',
    name: 'Heure & date',
    description: 'Une horloge locale lisible avec date, secondes et fuseau configurable.',
    category: 'Essentiels',
    icon: 'Clock3',
    version: '0.1.0',
    size: { min: { w: 2, h: 2 }, default: { w: 3, h: 3 }, max: { w: 6, h: 5 } },
    capabilities: [],
    configSchema: { format: ['24h', '12h'], showSeconds: 'boolean', timezone: 'IANA string' },
    refreshSeconds: 0,
    configSchemaVersion: 1,
  },
  {
    id: 'notes',
    name: 'Notes',
    description:
      'Une note locale modifiable, sauvegardée automatiquement et utilisable hors ligne.',
    category: 'Organisation',
    icon: 'StickyNote',
    version: '0.1.0',
    size: { min: { w: 3, h: 3 }, default: { w: 4, h: 4 }, max: { w: 12, h: 12 } },
    capabilities: ['storage'],
    configSchema: { noteId: 'uuid' },
    refreshSeconds: 0,
    configSchemaVersion: 1,
  },
  {
    id: 'system',
    name: 'Système',
    description: 'CPU, mémoire, stockage, température et uptime du Raspberry Pi.',
    category: 'Système',
    icon: 'Cpu',
    version: '0.1.0',
    size: { min: { w: 3, h: 3 }, default: { w: 4, h: 4 }, max: { w: 8, h: 8 } },
    capabilities: ['system', 'realtime'],
    configSchema: {},
    refreshSeconds: 5,
    configSchemaVersion: 1,
  },
  {
    id: 'weather.current',
    name: 'Météo actuelle',
    description: 'Conditions actuelles Open-Meteo avec cache local et mode hors ligne.',
    category: 'Météo',
    icon: 'CloudSun',
    version: '0.1.0',
    size: { min: { w: 3, h: 3 }, default: { w: 4, h: 4 }, max: { w: 8, h: 7 } },
    capabilities: ['network'],
    configSchema: { location: 'string', latitude: 'number', longitude: 'number' },
    refreshSeconds: 900,
    configSchemaVersion: 1,
  },
  {
    id: 'weather.forecast',
    name: 'Prévisions météo',
    description: 'Prévisions horaires et quotidiennes adaptatives selon la taille du widget.',
    category: 'Météo',
    icon: 'CloudRainWind',
    version: '0.1.0',
    size: { min: { w: 4, h: 3 }, default: { w: 8, h: 4 }, max: { w: 12, h: 8 } },
    capabilities: ['network'],
    configSchema: { location: 'string', latitude: 'number', longitude: 'number' },
    refreshSeconds: 900,
    configSchemaVersion: 1,
  },
  {
    id: 'sensor.temperature',
    name: 'Température capteur',
    description: 'Température intérieure ou extérieure provenant du bus de capteurs HomeDash.',
    category: 'Maison',
    icon: 'Thermometer',
    version: '0.1.0',
    size: { min: { w: 2, h: 2 }, default: { w: 3, h: 3 }, max: { w: 6, h: 6 } },
    capabilities: ['sensors', 'realtime'],
    configSchema: { sensorId: 'string' },
    refreshSeconds: 10,
    configSchemaVersion: 1,
  },
  {
    id: 'network',
    name: 'Réseau',
    description: 'Connexion Internet, latence, adresses locales et disponibilité du serveur.',
    category: 'Système',
    icon: 'Wifi',
    version: '0.1.0',
    size: { min: { w: 3, h: 2 }, default: { w: 4, h: 3 }, max: { w: 7, h: 6 } },
    capabilities: ['network', 'system'],
    configSchema: {},
    refreshSeconds: 15,
    configSchemaVersion: 1,
  },
  {
    id: 'calendar',
    name: 'Google Calendar',
    description: 'Événements à venir et gestion de Google Calendar depuis HomeDash.',
    category: 'Organisation',
    icon: 'CalendarDays',
    version: '0.1.0',
    size: { min: { w: 4, h: 3 }, default: { w: 8, h: 5 }, max: { w: 12, h: 12 } },
    capabilities: ['calendar', 'network'],
    configSchema: { calendarIds: 'string[]' },
    refreshSeconds: 300,
    configSchemaVersion: 1,
  },
];

export function getWidgetManifest(widgetId: string): WidgetManifest | undefined {
  return widgetCatalog.find((widget) => widget.id === widgetId);
}
